version: "3"
services:
    db:
      image: wda/db
      container_name: wda-cloud-base-postgresql-container
      environment:
        POSTGRES_DB: shucheng
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        PGDATA: /var/lib/postgresql/data
      ports:
        - 15433:5432
      volumes:
        - /www/wda_database:/var/lib/postgresql/data
