version: "3"
services:
    db:
      image: postgres:10.15
      container_name: shucheng-layout2-db
      environment:
        POSTGRES_DB: shucheng-layout2
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        PGDATA: /var/lib/postgresql/data
      ports:
        - "15434:5432"
      volumes:
        - ../db_data/layout2_database:/var/lib/postgresql/data
